version: '3'

services:
  mysql-standalone:
    image: gfrgt/mysql:latest
    container_name: mysql


  springboot:
    image: gfrgt/backend:latest
    container_name: springboot
    ports:
      - 8080:8080


  frontend-angular:
    image: gfrgt/clientag:latest
    container_name: frontend-angular
    ports:
      - 80:80
